/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_1111563_6[] = { 3, 10 };

// (before - mean) / scale
const float ei_classifier_anom_scale_1111563_6[2] = { 0.5230782797840418, 0.8414810532697417 };
const float ei_classifier_anom_mean_1111563_6[2] = { 0.5411924793229781, 0.2797352621799904 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_1111563_6[32] = {
	{ ( float[2] ) { 0.46782007813453674, -0.05076920613646507 }, 0.2748285088947918 },
	{ ( float[2] ) { 1.4006879329681396, -0.05036274343729019 }, 0.296982211908949 },
	{ ( float[2] ) { -0.9624872207641602, -0.24485287070274353 }, 0.41203144624180293 },
	{ ( float[2] ) { 0.6658172011375427, -0.7957004308700562 }, 0.12880192296531132 },
	{ ( float[2] ) { 1.2640918493270874, -0.7743733525276184 }, 0.06739333609541893 },
	{ ( float[2] ) { -0.06794768571853638, -0.3271804749965668 }, 0.246813841520062 },
	{ ( float[2] ) { 0.8329516649246216, 0.010800113901495934 }, 0.3219823728761329 },
	{ ( float[2] ) { -1.7730693817138672, 0.2409713864326477 }, 0.3964951933011197 },
	{ ( float[2] ) { 0.17435334622859955, 1.0343399047851562 }, 0.4467474041189529 },
	{ ( float[2] ) { -0.5734347105026245, -0.34909623861312866 }, 0.2641778568143746 },
	{ ( float[2] ) { -1.0551434755325317, -0.7854660153388977 }, 0.4130567227387743 },
	{ ( float[2] ) { -1.6275533437728882, 0.9324472546577454 }, 0.5811710245276839 },
	{ ( float[2] ) { 1.2647689580917358, -0.6156964898109436 }, 0.2630925493838178 },
	{ ( float[2] ) { -0.1434917449951172, 3.222374439239502 }, 0.5392353257244461 },
	{ ( float[2] ) { 0.7950338125228882, 2.1069188117980957 }, 0.45930084880563266 },
	{ ( float[2] ) { 1.9282591342926025, 0.11584950238466263 }, 0.49909926268191634 },
	{ ( float[2] ) { -0.3458722233772278, -0.29023146629333496 }, 0.25297883881634675 },
	{ ( float[2] ) { -0.4572097957134247, 0.5558764934539795 }, 0.5315605153094326 },
	{ ( float[2] ) { 0.06600777059793472, 1.7643824815750122 }, 0.46335874302570407 },
	{ ( float[2] ) { -1.294257640838623, 0.09821730852127075 }, 0.35258426832744094 },
	{ ( float[2] ) { -1.853616714477539, -0.43631547689437866 }, 0.3116048753375563 },
	{ ( float[2] ) { 0.1457347422838211, 2.4056122303009033 }, 0.5613859012540207 },
	{ ( float[2] ) { -0.8656806349754333, 1.6415849924087524 }, 0.8009501117995304 },
	{ ( float[2] ) { 0.13484911620616913, 0.10891200602054596 }, 0.4141101833956595 },
	{ ( float[2] ) { 0.8838055729866028, 1.1423453092575073 }, 0.583846085984109 },
	{ ( float[2] ) { -1.1143503189086914, 0.8091546893119812 }, 0.4379747943663573 },
	{ ( float[2] ) { 0.6648300290107727, -0.510827898979187 }, 0.20988581472689205 },
	{ ( float[2] ) { -1.044714093208313, 5.352476119995117 }, 2.081789850517839 },
	{ ( float[2] ) { -0.7676931023597717, 2.7156944274902344 }, 0.839313096875538 },
	{ ( float[2] ) { 1.3780605792999268, 1.4810881614685059 }, 0.37023818999612257 },
	{ ( float[2] ) { -0.9092762470245361, 3.894537925720215 }, 0.6869643246913265 },
	{ ( float[2] ) { -1.1290318965911865, 10.82562255859375 }, 0 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
