/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include <vector>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_1111563_4_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1111563_1[] = { "falling", "rising", "stable" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1111563_5_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_1111563_5_axes_size = 2;
ei_dsp_config_flatten_t ei_dsp_config_1111563_5 = {
    5, // uint32_t blockId
    1, // int implementationVersion
    2, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    true, // boolean rms
    true, // boolean stdev
    true, // boolean skewness
    true, // boolean kurtosis
    0 // int moving_avg_num_windows
};

const float ei_dn_standard_scaler_mean_1111563_5[14] = { 25.77603783777268, 25.720574463188374, 25.837220904669323, 25.7762852421087, 0.03844518701797319, 0.1670319936124172, 0.12667884533828433, 0.003852806298642327, -0.03963769877337338, 0.05182639325235816, 0.037030628440059304, 0.02844654236848235, 0.05810894246745616, 0.10939635110560146 };
const float ei_dn_standard_scaler_scale_1111563_5[14] = { 0.07933464495135359, 0.07925117619521117, 0.07941440554874946, 0.07933486700520108, 9.810937964548081, 1.1034376080921764, 0.6130452402871505, 17.41766746561156, 9.117642040869828, 5.987866368303545, 10.710046477841479, 12.943449840089652, 1.3974432722718033, 0.7650030568943962 };
const float ei_dn_standard_scaler_var_1111563_5[14] = { 158.88183061534187, 159.21668122893468, 158.5628419945455, 158.88094121390358, 0.0103891242601741, 0.8213049426277407, 2.6608166544975713, 0.003296248994525812, 0.012029149556967881, 0.027890467939310003, 0.008718008516879702, 0.005968977061992041, 0.5120727030585035, 1.708730843978176 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1111563_5 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1111563_5,
    .mean_data_len = 14,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1111563_5,
    .scale_data_len = 14,
    .var_data = (float *)ei_dn_standard_scaler_var_1111563_5,
    .var_data_len = 14
};
ei_data_normalization_t ei_data_normalization_config_1111563_5 = {
    (void *) &ei_data_normalization_standard_scaler_config_1111563_5, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1111563_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1111563_1[ei_dsp_blocks_1111563_1_size] = {
    { // DSP block 5
        5,
        14, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_1111563_5, // pointer to config struct
        ei_dsp_config_1111563_5_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1111563_5_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_1111563_5, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1111563_4 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1111563_4_init,
    .model_invoke = &tflite_learn_1111563_4_invoke,
    .model_reset = &tflite_learn_1111563_4_reset,
    .model_input = &tflite_learn_1111563_4_input,
    .model_output = &tflite_learn_1111563_4_output,
};

const uint8_t ei_output_tensors_indices_1111563_4[1] = { 0 };
const uint8_t ei_output_tensors_size_1111563_4 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1111563_4 = {
    .implementation_version = 1,
    .block_id = 4,
    .output_tensors_indices = ei_output_tensors_indices_1111563_4,
    .output_tensors_size = ei_output_tensors_size_1111563_4,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1111563_4,
    .dequantize_output = 0,
};

const ei_learning_block_config_anomaly_kmeans_t ei_learning_block_config_1111563_6 = {
    .implementation_version = 1,
    .block_id = 6,
    .anom_axis = ei_classifier_anom_axes_1111563_6,
    .anom_axes_size = 2,
    .anom_clusters = ei_classifier_anom_clusters_1111563_6,
    .anom_cluster_count = 32,
    .anom_scale = ei_classifier_anom_scale_1111563_6,
    .anom_mean = ei_classifier_anom_mean_1111563_6,
};

const uint8_t ei_learning_blocks_1111563_1_size = 2;
const uint32_t ei_learning_block_1111563_4_inputs[1] = { 5 };
const uint8_t ei_learning_block_1111563_4_inputs_size = 1;
const uint32_t ei_learning_block_1111563_6_inputs[1] = { 5 };
const uint8_t ei_learning_block_1111563_6_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1111563_1[ei_learning_blocks_1111563_1_size] = {
    {
        4,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1111563_4,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1111563_4_inputs,
        ei_learning_block_1111563_4_inputs_size,
    },
    {
        6,
        &run_kmeans_anomaly,
        (void*)&ei_learning_block_config_1111563_6,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1111563_6_inputs,
        ei_learning_block_1111563_6_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1111563_4 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1111563_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1111563_1[ei_postprocessing_blocks_1111563_1_size] = {
    {
        .block_id = 4,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1111563_4,
        .input_block_id = 4
    },
};

const uint8_t freeform_outputs_1111563_1_size = 0;

uint32_t *freeform_outputs_1111563_1 = nullptr;

const ei_impulse_t impulse_1111563_1 = {
    .project_id = 1111563,
    .project_owner = "Di_nesh",
    .project_name = "RiverSense-AI",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 3,

    .nn_input_frame_size = 14,
    .raw_sample_count = 10,
    .raw_samples_per_frame = 2,
    .dsp_input_frame_size = 10 * 2,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 500,
    .frequency = 2,

    .dsp_blocks_size = ei_dsp_blocks_1111563_1_size,
    .dsp_blocks = ei_dsp_blocks_1111563_1,

    .learning_blocks_size = ei_learning_blocks_1111563_1_size,
    .learning_blocks = ei_learning_blocks_1111563_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1111563_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1111563_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "distance + delta",
    .slice_size = (10/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_KMEANS,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_1111563_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1111563_1_size,
    .freeform_outputs = freeform_outputs_1111563_1
};

ei_impulse_handle_t impulse_handle_1111563_1 = ei_impulse_handle_t( &impulse_1111563_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1111563_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1111563_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1111563_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1111563_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
